export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'

// export const FETCH_TODOS_STARTED = 'FETCH_TODOS_STARTED'
// export const FETCH_TODOS_SUCCEEDED = 'FETCH_TODOS_SUCCEEDED'
// export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED'